### ISSUE TITLE
Promote to guide

### ISSUE THREAD

**Issue by That1G** [wowdev-raven/Dungeon-Crawler-Reports#15]
There is a chance while queuing that you will become the leader or "guide" if this is the case the bot will attempt to follow itself... This is clearly not a good thing and as such the bot should promote another player of the group to guide.

**Comment by TheSmokie** [comment]
Are you sure? i have the settings set to not que for leader.
 Lua.LuaDoString($"SetLFGRoles(false, {DCrawler.CurrentSetting.Tank.ToString().ToLower()}, {DCrawler.CurrentSetting.Heal.ToString().ToLower()}, {DCrawler.CurrentSetting.DPS.ToString().ToLower()});");

First false is for lead / guide Lua exp : SetLFGRoles(isLeader, isTank, isHealer, isDPS) - changes the selected roles

for now i will make it follow tank only. using tank code.
