### ISSUE TITLE
Resurrect

### ISSUE THREAD

**Issue by That1G** [wowdev-raven/Dungeon-Crawler-Reports#18]
The bot currently will not take a res if given by someone 

(I assume it will also not currently take a soulstone or shaman res either)

**Comment by TheSmokie** [comment]
I will add hook to RESURRECT_REQUEST event with
AcceptResurrect(); 
When I get home.

**Comment by TheSmokie** [comment]
Added : 
`        if(LuaEventHooks.ToString() == "RESURRECT_REQUEST")
        {
            Lua.LuaDoString("AcceptResurrect();");
        }
`
