### ISSUE TITLE
Stat weights 

### ISSUE THREAD

**Issue by That1G** [wowdev-raven/Dungeon-Crawler-Reports#6]
Add an option box for stat weights,
List of useful stats:

Strength
Agility
Stamina
Intellect
Spirit
Attack power
Spell Power
Haste
Critical Strike
(Weapon)
   * Weapon damage
   * Weapon speed ?

**Comment by TheSmokie** [comment]
`Strength Added
Agility Added
Stamina Added
Intellect Added
Spirit Added
Attack power Added
Spell Power Added
Haste Added
Critical Strike Added`
