### ISSUE TITLE
Adjustable rolling

### ISSUE THREAD

**Issue by That1G** [wowdev-raven/Dungeon-Crawler-Reports#7]
Allow the rolling (Greed, Need, Pass, DE) to be adjustable, such as allowing the user to input a wait time before the bot rolls (Can be static or a random time) and allow the user to select greed/need/pass/DE on any items. (Such as telling my bot to need on everything (for whatever the reason) Or to greed on everything, or to DE on all green items, or to pass on all blues.

 (Stat weights should override these settings and the bot should always need items that are "better" for the bot.)

**Comment by TheSmokie** [comment]
Completed.
