### ISSUE TITLE
Healer targetting

### ISSUE THREAD

**Issue by That1G** [wowdev-raven/Dungeon-Crawler-Reports#9]
Have the healer version actually target players (importantly the players it's currently healing) instead of the boss.

Saw this behavior when you showed me it healing.

**Comment by TheSmokie** [comment]
Question : does it really matter if its targetting players vs the boss? This is more handled by fightclass. i am guessing the fightclass is using "CastSpellByName(spellname, unitname);"

**Comment by That1G** [comment]
"does it really matter" overall... No, but in terms of looking more like a human and not a bot, this is something that can do that. Some good healers use mouseover macros to heal so it's totally possible to see this from a normal player, but that player also normally attacks the boss whenever they have the chance.
